"""drop_payment_requests

Revision ID: 6db2f6afae6d
Revises: 1f88001b814e
Create Date: 2026-02-15 23:40:45.738492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6db2f6afae6d'
down_revision: Union[str, Sequence[str], None] = '1f88001b814e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop payment_request_id column (with its index and FK) from transactions
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_payment_request_id')
        batch_op.drop_constraint('fk_txn_payment_request_id', type_='foreignkey')
        batch_op.drop_column('payment_request_id')

    # Drop payment_requests table
    op.drop_index('ix_payment_requests_merchant_id', table_name='payment_requests')
    op.drop_table('payment_requests')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_request_id', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_txn_payment_request_id'), 'payment_requests', ['payment_request_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_transactions_payment_request_id'), ['payment_request_id'], unique=False)

    op.create_table('payment_requests',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('merchant_id', sa.VARCHAR(), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_requests_merchant_id'), ['merchant_id'], unique=False)

    # ### end Alembic commands ###
